package quizzes;

import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.servlet.RequestDispatcher;
import javax.servlet.ServletContext;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import dbconnection.DBConnection;

/**
 * Servlet implementation class CreateQuiz
 */
@WebServlet("/CreateQuiz")
public class CreateQuiz extends HttpServlet {
	
	private static final long serialVersionUID = 1L;
       
    /**
     * @see HttpServlet#HttpServlet()
     */
    public CreateQuiz() {
        super();
        // TODO Auto-generated constructor stub
    }

	/**
	 * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
	}

	/**
	 * @see HttpServlet#doPost(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		String formID = request.getParameter("formID");
		ServletContext context = request.getServletContext();
		DBConnection connection = (DBConnection) context.getAttribute("dbconnection");
		if(formID.equals("initialize_quiz")){
			InitializeQuiz(request, connection);
		}
		if(formID.equals("quiz_info")){
			
		}
		if(formID.equals("multiple_choice")){
			Question.NewMultipleChoice(request);
		}
		if(formID.equals("fill_in_the_blank")){
			Question.NewFillInTheBlank(request);
		}
		if(formID.equals("question_response")){
			Question.NewQuestionResponse(request);
		}
		if(formID.equals("picture_response")){
			Question.NewPictureResponse(request);
		}
		
		RequestDispatcher dispatch = request.getRequestDispatcher("CreateQuiz.jsp");
		dispatch.forward(request, response);
	}
	
	/**
	 * Creates a new quiz in the database, ready and prepared to be edited
	 * and filled out with questions. 
	 * @param request
	 * @param connection
	 */
	private void InitializeQuiz(HttpServletRequest request, DBConnection connection){
		ResultSet rs = connection.executeQuery("INSERT INTO quizzes(title) values(\"\")");
		AddQuizAsSessionAttr(request, rs);
	}
	
	/**
	 * Makes id to quiz which is currently being created a session
	 * attribute. Not all the information has yet been stored in the quiz, so
	 * this allows the servlet to access the quiz to edit it and to add questions
	 * to it in the questions tables 
	 * @param rs
	 */
	private void AddQuizAsSessionAttr(HttpServletRequest request,ResultSet rs){
		int id = 0;
		try {
			//Get the autogenerated quiz id
			rs.next();
			id = rs.getInt(1);
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		HttpSession session = request.getSession();
		session.setAttribute("quiz_being_created", id);
	}

}
